---
language: ruby
sudo: false
before_install:
  - gem install bundler
  - "rm -f ${BUNDLE_GEMFILE}.lock"
before_script:
  - bundle update
cache: bundler
rvm:
- 2.5.1
- ruby-head
- rbx-2
- jruby
gemfile:
- gemfiles/rails_4.2.gemfile
- gemfiles/rails_5.0.gemfile
- gemfiles/rails_5.1.gemfile
matrix:
  include:
  - rvm: 2.5.1
    gemfile: gemfiles/rails_4.2.gemfile
  - rvm: 2.5.1
    gemfile: gemfiles/rails_5.1.gemfile
  - rvm: 2.5.1
    gemfile: gemfiles/rails_5.2.gemfile
  allow_failures:
  - rvm: rbx-2
  - rvm: jruby
  - rvm: ruby-head
  fast_finish: true
notifications:
  email: false
